import { events, sponsorPackages } from '@/lib/data';
import type { CmsContent } from './schema';

export const defaultCmsContent: CmsContent = {
  theme: {
    background: '#090604',
    foreground: '#f4ede3',
    accent: '#ff7a00',
    accentStrong: '#d86000',
    accentSoft: '#f6b94f',
    surface: '#15110e',
    surfaceAlt: '#1f1814',
    border: '#3f2a1b',
    muted: '#b8a48e',
    boxLabelFont: 'exo',
    boxTitleFont: 'cinzel',
    boxBodyFont: 'exo',
    boxLabelSize: '10pt',
    boxTitleSize: '18pt',
    boxBodySize: '12pt',
  },
  site: {
    seo: {
      title: 'Headbang Handwerk – Handwerk trifft Metal',
      description:
        'Wir bringen das Handwerk auf die lautesten Festivals Europas – für Nachwuchs, Sichtbarkeit und ein unvergessliches Erlebnis.',
      keywords: ['Handwerk', 'Metal', 'Festival', 'Sponsoring', 'Nachwuchs', 'Wacken', 'Summer Breeze'],
    },
    logo: {
      assetUrl: '',
      assetName: '',
      assetContentType: '',
    },
    navigationLinks: [
      { id: 'home', label: 'Startseite', href: '/', placement: 'primary' },
      { id: 'about', label: 'Über uns', href: '/ueber-uns', placement: 'primary' },
      { id: 'events', label: 'Veranstaltungen', href: '/veranstaltungen', placement: 'primary' },
      { id: 'membership', label: 'Mitglied werden', href: '/formular', placement: 'primary' },
      { id: 'partners', label: 'Partner', href: '/unsere-partner', placement: 'primary' },
      { id: 'shop', label: 'Shop', href: '/merchandise', placement: 'primary' },
      { id: 'sponsor', label: 'Sponsor werden', href: '/sponsoren', placement: 'more' },
      { id: 'donation', label: 'Spenden', href: '/spenden', placement: 'more' },
      { id: 'game', label: 'Spiele', href: '/game', placement: 'more' },
    ],
    navigationCtaLabel: 'Jetzt unterstützen',
    navigationCtaHref: '/sponsoren',
    events,
    sponsorPackages,
    partners: [],
    liveEditor: {
      richText: {},
      boxStyles: {},
    },
    home: {
      heroBadge: 'Startseite mit klarem Projektfokus',
      heroTitle: 'Handwerk trifft Metal. Leidenschaft trifft Zukunft.',
      heroSubtitle: 'Handwerk. Laut. Sichtbar.',
      heroDescription:
        'Wir bringen das Handwerk dorthin, wo Energie, Gemeinschaft und Begeisterung aufeinandertreffen: auf große Bühnen, zu echten Begegnungen und mitten in eine Kultur, die Leidenschaft sichtbar macht.',
      heroLead:
        'Wir bringen das Handwerk dorthin, wo Energie, Gemeinschaft und Begeisterung aufeinandertreffen – auf die größten Metal-Festivals Europas.',
      heroBody:
        'Mit Headbang Handwerk e.V. schaffen wir eine Plattform, die zeigt, wie modern, vielseitig und kraftvoll das Handwerk wirklich ist. Zwischen Bühne, Feuer und tausenden Festivalbesuchern entsteht ein Ort, an dem echtes Können erlebbar wird: live, zum Anfassen und zum Mitmachen.',
      heroPrimaryCtaLabel: 'Veranstaltungen entdecken',
      heroPrimaryCtaHref: '/veranstaltungen',
      heroSecondaryCtaLabel: 'Mitglied werden',
      heroSecondaryCtaHref: '/formular',
      heroMetrics: [
        { value: 'Wacken 2027', label: 'Nächster großer Meilenstein im Projekt' },
        { value: 'Live-Demos', label: 'Handwerk als Erlebnis statt nur als Botschaft' },
        { value: 'Partnernetzwerk', label: 'Betriebe, Innungen und Unterstützer an einem Ort' },
      ],
      projectFocusEyebrow: 'Projektfokus',
      projectFocusTitle: 'Wacken Open Air 2027',
      projectFocusText:
        'Der nächste große Schritt ist ein eigener Stand mit starken Partnern, sichtbaren Aktionen und einer klaren Botschaft: Handwerk gehört mitten ins Leben und auf große Bühnen.',
      projectFocusToneLabel: 'Ansprache',
      projectFocusToneValue: 'Laut. Echt. Nahbar.',
      projectFocusImpactLabel: 'Wirkung',
      projectFocusImpactValue: 'Erlebnis statt Bannerdenken',
      stats: [
        { value: '2027', label: 'Zieljahr für den nächsten großen Wacken-Auftritt' },
        { value: '3+', label: 'Festivalformate bereits in Planung oder Vorbereitung' },
        { value: '4', label: 'Sponsoring-Stufen für unterschiedliche Partnerziele' },
        { value: '100%', label: 'Fokus auf echtes Erleben statt austauschbarer Werbung' },
      ],
      focusEyebrow: 'Unser Ziel ist klar',
      focusTitle: 'Handwerk sichtbar machen.',
      focusPoints: [
        'Nachwuchs begeistern',
        'Handwerk sichtbar machen',
        'Unternehmen eine neue Bühne bieten',
      ],
      promiseCards: [
        {
          title: 'Als Erlebnis, nicht als Pflicht',
          text: 'Gemeinsam mit Partnern aus der Wirtschaft, Innungen und Betrieben präsentieren wir das Handwerk nicht als Pflicht – sondern als Erlebnis.',
          icon: 'flame',
        },
        {
          title: 'Laut. Ehrlich. Leidenschaftlich.',
          text: 'Ob durch interaktive Aktionen, Live-Demonstrationen oder innovative Standkonzepte: Wir zeigen, dass Handwerk genauso laut, ehrlich und leidenschaftlich ist wie die Musik, die diese Festivals prägt.',
          icon: 'users',
        },
      ],
      processEyebrow: 'So funktioniert die Beteiligung',
      processTitle: 'Vom Interesse bis zur Festivalpräsenz.',
      processLead:
        'Die Startseite führt jetzt klarer durch das Projekt: zuerst der Nutzen, dann der Ablauf, danach die konkreten Einstiegspunkte für Sponsoren und Unterstützer.',
      processSteps: [
        {
          number: '01',
          title: 'Projekt auswählen',
          text: 'Du entscheidest, ob du Wacken 2027, kommende Festivals oder einzelne Aktivierungen unterstützen willst.',
        },
        {
          number: '02',
          title: 'Passendes Paket finden',
          text: 'Von sichtbarer Grundpräsenz bis zur prominenten Partnerrolle stimmen wir die Beteiligung auf dein Ziel ab.',
        },
        {
          number: '03',
          title: 'Aktivierung gemeinsam planen',
          text: 'Wir übersetzen Marke, Gewerk und Botschaft in einen Auftritt, der im Festival funktioniert.',
        },
        {
          number: '04',
          title: 'Vor Ort Wirkung erzeugen',
          text: 'Am Stand entstehen Erlebnisse, Gespräche, Content und Kontakte, die weit über das Festival hinaus wirken.',
        },
      ],
      whyEyebrow: 'Warum das funktioniert',
      whyTitle: 'Handwerk wird nicht erklärt. Es wird erlebt.',
      whyBody:
        'Genau darin liegt das Prinzip dieser Startseite: Sie stellt nicht zuerst Details aus, sondern das Ergebnis. Wer hier landet, versteht direkt, worum es geht, warum das Projekt relevant ist und wie man konkret Teil davon wird.',
      whyBusinessLabel: 'Für Betriebe',
      whyBusinessText: 'Mehr Sichtbarkeit, stärkere Differenzierung und neue Gesprächsanlässe.',
      whyYouthLabel: 'Für Nachwuchs',
      whyYouthText: 'Ein direkter, ungezwungener Zugang zu Berufen, Menschen und echtem Können.',
      updateEyebrow: 'Aktuelle Information',
      updateTitle: 'Wacken 2027 steht im Fokus.',
      updateParagraphs: [
        'Headbang Handwerk plant den nächsten großen Schritt: einen eigenen Stand auf dem Wacken Open Air 2027.',
        'Mit Live-Demos, Mitmach-Aktionen und starken Partnern entsteht ein Format, das Handwerk nicht kleiner erklärt, sondern größer inszeniert.',
        'Gesucht werden Unternehmen, Unterstützer und Branchenpartner, die früh Teil dieses Projekts werden wollen.',
      ],
      newsTitle: 'News',
      newsParagraphs: [
        'Hier könnt ihr aktuelle Neuigkeiten, Ankündigungen und wichtige Updates direkt auf der Startseite veröffentlichen.',
      ],
      newsImages: [],
      newsImagePositionX: 50,
      newsImagePositionY: 50,
      heroImageAlt: 'Headbang Handwerk auf einem Festival',
      heroImagePositionX: 50,
      heroImagePositionY: 40,
      eventsSectionTitle: 'Nächste Veranstaltungen',
      eventsSectionIntro: 'Drei kommende Termine aus unserer Veranstaltungsverwaltung. Für mehr Details geht es direkt zur Übersicht.',
      eventsSectionCtaLabel: 'Alle Veranstaltungen',
      eventsEmptyText: 'Sobald kommende Veranstaltungen mit strukturiertem Datum hinterlegt sind, erscheinen sie hier automatisch.',
      newsSectionTitle: 'Aktuelles aus dem Verein',
      newsSectionIntro: 'Aktuelle Neuigkeiten, Einblicke und Hinweise aus dem Verein.',
      newsEmptyText: 'Aktuell gibt es noch keine veröffentlichten Neuigkeiten.',
      newsItems: [],
      membershipTitle: 'Wir brauchen Menschen, die etwas bewegen.',
      membershipBody:
        'Werde Teil von Headbang Handwerk und unterstütze uns dabei, das Handwerk sichtbar, erlebbar und zukunftsfähig zu machen.',
      membershipCtaLabel: 'Jetzt Mitglied werden',
      membershipCtaHref: '/formular',
      membershipImage: {
        assetUrl: '',
        assetName: '',
        assetContentType: '',
      },
      membershipImageAlt: 'Mitgliederbereich Headbang Handwerk',
      membershipImagePositionX: 50,
      membershipImagePositionY: 50,
      displaySettings: {
        heroHeightDesktop: 640,
        heroHeightMobile: 460,
        heroTitleSizeDesktop: 76,
        heroTitleSizeMobile: 40,
        sectionTitleSizeDesktop: 44,
        sectionTitleSizeMobile: 30,
        sectionSpacingDesktop: 104,
        sectionSpacingMobile: 72,
        cardGap: 24,
        eventImageHeight: 240,
        newsImageHeight: 220,
        membershipMinHeight: 400,
      },
      updatePrimaryCtaLabel: 'Sponsoring ansehen',
      updatePrimaryCtaHref: '/sponsoren',
      updateSecondaryCtaLabel: 'Kontakt aufnehmen',
      updateSecondaryCtaHref: '/kontakt',
      eventsEyebrow: 'Nächste Anlässe',
      eventsTitle: 'Veranstaltungen mit echter Bühne für das Handwerk.',
      eventsCtaLabel: 'Alle Termine ansehen',
      eventsCtaHref: '/veranstaltungen',
      packagesEyebrow: 'Einstieg für Partner',
      packagesTitle: 'Sponsoring-Pakete mit klarer Staffelung.',
      packagesCtaLabel: 'Alle Pakete im Detail',
      packagesCtaHref: '/sponsoren',
      closingEyebrow: 'Werde Teil der Bewegung',
      closingTitle: 'Unterstütze uns dabei, das Handwerk neu zu denken und sichtbar zu machen.',
      closingLead:
        'Als Partner, Sponsor oder Unterstützer bringst du deine Marke dorthin, wo echte Aufmerksamkeit entsteht – mitten ins Leben.',
      closingStatement: 'Headbang Handwerk – weil echtes Handwerk keine Bühne braucht.\nWir bauen sie einfach.',
      closingPrimaryCtaLabel: 'Jetzt unterstützen',
      closingPrimaryCtaHref: '/sponsoren',
      closingSecondaryCtaLabel: 'Ansprechpartner kontaktieren',
      closingSecondaryCtaHref: '/kontakt',
      heroImage: {
        assetUrl: '',
        assetName: '',
        assetContentType: '',
      },
      backgroundImage: {
        assetUrl: '',
        assetName: '',
        assetContentType: '',
      },
      instagramVideo: {
        assetUrl: '',
        assetName: '',
        assetContentType: '',
      },
    },
    sponsors: {
      title: 'Sponsoring',
      accentWord: 'Pakete',
      lead:
        'Bringt eure Marke auf die Hauptbühne des deutschen Handwerks – inmitten der lautesten Festivals Europas.',
      benefitsTitle: 'Was ihr bekommt',
      benefits: [
        'Direkte Ansprache der Zielgruppe auf Festivals',
        'Logo auf Website, Banner und Social Media',
        'Auf Wunsch Spendenquittung (kein Verein, steuerlich klären)',
        'Persönliche Betreuung durch unser Team',
        'Flexibel buchbar – einzelne Festivals oder Gesamtsaison',
        'Hohes Medien- und Social-Media-Potenzial',
      ],
      customPackageTitle: 'Individuelles Paket gewünscht?',
      customPackageText:
        'Ihr habt besondere Anforderungen oder wollt etwas ganz Eigenes? Wir erstellen euch gerne ein maßgeschneidertes Angebot.',
      customPackageCtaLabel: 'Jetzt anfragen',
      customPackageCtaHref: '/kontakt',
    },
    about: {
      title: 'Über',
      accentWord: 'uns',
      introParagraphs: [
        'Headbang Handwerk wurde mit einer einfachen Idee gegründet: Das Handwerk braucht neue Wege, um junge Menschen zu begeistern. Und Festivals sind genau der richtige Ort dafür.',
        'Wir sind ein Team aus Handwerksbegeisterten und Metal-Fans, das glaubt: Wer einmal live gesehen hat, wie eine Klinge geschmiedet wird oder wie ein Zimmermann arbeitet, der vergisst das nicht mehr. Genau das wollen wir zeigen – laut, lebendig, unvergesslich.',
      ],
      values: [
        {
          title: 'Leidenschaft',
          description: 'Wir lieben Metal und Handwerk gleichermaßen – und das spürt man bei allem, was wir tun.',
        },
        {
          title: 'Mission',
          description: 'Nachwuchs fürs Handwerk gewinnen, dort wo die Jugend wirklich ist: auf Festivals.',
        },
        {
          title: 'Vision',
          description: 'Headbang Handwerk europaweit auf allen großen Metal-Festivals etablieren.',
        },
      ],
      sections: [
        {
          eyebrow: 'Wer wir sind',
          title: 'Eine Plattform zwischen Bühne und Handwerk.',
          paragraphs: [
            'Mit Headbang Handwerk e.V. schaffen wir eine Plattform, die zeigt, wie modern, vielseitig und kraftvoll das Handwerk wirklich ist.',
            'Zwischen Bühne, Feuer und tausenden Festivalbesuchern entsteht ein Ort, an dem echtes Können erlebbar wird: live, zum Anfassen und zum Mitmachen.',
          ],
        },
        {
          eyebrow: 'Warum alles entstanden ist',
          title: 'Neue Wege für die Nachwuchsgewinnung.',
          paragraphs: [
            'Headbang Handwerk wurde mit einer einfachen Idee gegründet: Das Handwerk braucht neue Wege, um junge Menschen zu begeistern. Und Festivals sind genau der richtige Ort dafür.',
          ],
        },
        {
          eyebrow: 'Unsere Vision',
          title: 'Eine europaweit sichtbare Festivalpräsenz.',
          paragraphs: [
            'Headbang Handwerk europaweit auf allen großen Metal-Festivals etablieren.',
            'Der nächste große Schritt ist ein eigener Stand mit starken Partnern, sichtbaren Aktionen und einer klaren Botschaft: Handwerk gehört mitten ins Leben und auf große Bühnen.',
          ],
        },
        {
          eyebrow: 'Unsere Mission',
          title: 'Handwerk als Erlebnis statt als Pflichtgefühl.',
          paragraphs: [
            'Nachwuchs fürs Handwerk gewinnen, dort wo die Jugend wirklich ist: auf Festivals.',
            'Gemeinsam mit Partnern aus der Wirtschaft, Innungen und Betrieben präsentieren wir das Handwerk nicht als Pflicht – sondern als Erlebnis.',
          ],
        },
        {
          eyebrow: 'Unsere Ziele',
          title: 'Sichtbarkeit, Nachwuchs und echte Beteiligung.',
          paragraphs: [
            'Unser Ziel ist klar: Handwerk sichtbar machen.',
          ],
          bullets: [
            'Nachwuchs begeistern',
            'Handwerk sichtbar machen',
            'Unternehmen eine neue Bühne bieten',
          ],
        },
        {
          eyebrow: 'Warum Handwerk und Metal zusammenpassen',
          title: 'Handwerk wird nicht erklärt. Es wird erlebt.',
          paragraphs: [
            'Wer einmal live gesehen hat, wie eine Klinge geschmiedet wird oder wie ein Zimmermann arbeitet, der vergisst das nicht mehr.',
            'Ob durch interaktive Aktionen, Live-Demonstrationen oder innovative Standkonzepte: Wir zeigen, dass Handwerk genauso laut, ehrlich und leidenschaftlich ist wie die Musik, die diese Festivals prägt.',
          ],
        },
      ],
      teamTitle: 'Menschen hinter dem Verein',
      teamLead:
        'Wir sind ein Team aus Handwerksbegeisterten und Metal-Fans, das Leidenschaft, Organisation und Festivalenergie in ein gemeinsames Projekt übersetzt.',
      teamRoles: ['Gründer & Projektleitung', 'Marketing & Social Media', 'Technik & Aufbau'],
      teamImages: [
        {
          assetUrl: '',
          assetName: '',
          assetContentType: '',
        },
        {
          assetUrl: '',
          assetName: '',
          assetContentType: '',
        },
        {
          assetUrl: '',
          assetName: '',
          assetContentType: '',
        },
      ],
      teamMembers: [
        {
          role: 'Gründer & Projektleitung',
          description: '',
          image: {
            assetUrl: '',
            assetName: '',
            assetContentType: '',
          },
          imageAlt: 'Teammitglied aus der Projektleitung von Headbang Handwerk',
        },
        {
          role: 'Marketing & Social Media',
          description: '',
          image: {
            assetUrl: '',
            assetName: '',
            assetContentType: '',
          },
          imageAlt: 'Teammitglied aus Marketing und Social Media von Headbang Handwerk',
        },
        {
          role: 'Technik & Aufbau',
          description: '',
          image: {
            assetUrl: '',
            assetName: '',
            assetContentType: '',
          },
          imageAlt: 'Teammitglied aus Technik und Aufbau von Headbang Handwerk',
        },
      ],
      closingEyebrow: 'Mitmachen',
      closingTitle: 'Wir brauchen Menschen, die etwas bewegen.',
      closingBody:
        'Werde Teil von Headbang Handwerk und unterstütze uns dabei, das Handwerk sichtbar, erlebbar und zukunftsfähig zu machen.',
      ctaLabel: 'Jetzt Mitglied werden',
      ctaHref: '/formular',
    },
    contact: {
      title: 'Kontakt',
      lead:
        'Habt ihr Fragen, wollt ihr Sponsor werden oder sucht ihr eine Bannerfläche? Schreibt uns – wir antworten innerhalb von 1–2 Werktagen.',
      email: 'info@headbang-handwerk.com',
      instagramLabel: '@headbanghandwerk',
      facebookLabel: 'Headbang Handwerk',
      formTitle: 'Nachricht senden',
    },
    stand: {
      badge: 'Messestand-Konfiguration',
      title: '3D-Stand &',
      accentWord: 'Bannerflächen',
      lead:
        'Wählt eure Wunschposition am Stand und sichert euch maximale Sichtbarkeit auf unseren Festivals. Klickt auf eine Fläche für Details.',
      overviewTitle: 'Stand-Übersicht (Schematisch)',
      overviewPlaceholderTitle: 'Interaktive 3D-Ansicht',
      overviewPlaceholderText: 'folgt in Kürze',
      assetUrl: '',
      assetName: '',
      assetContentType: '',
      frontBannerLabel: 'Frontbanner (3×2m) – €800',
      backBannerLabel: 'Rückbanner (4×1m) – €350',
      leftLabel: 'Links',
      rightLabel: 'Rechts ⚡',
      availableTitle: 'Verfügbare Flächen',
      reservedTitle: 'Reserviert / Vergeben',
    },
    merchandise: {
      eyebrow: 'Merchandise',
      title: 'Shirts, Hoodies und mehr für Headbang Handwerk.',
      lead: 'Festival-ready Merch mit Varianten, Warenkorb und sicherem Stripe-Checkout. Wähle deine Artikel aus, prüfe deinen Warenkorb und gehe dann gesammelt zur Kasse.',
      products: [
        {
          id: 'festival-shirt-black',
          name: 'Festival Shirt Blackout',
          description: 'Schwarzes Unisex-Shirt mit Headbang-Handwerk-Frontprint für Bühne, Stand und Alltag.',
          price: 29,
          sizes: ['S', 'M', 'L', 'XL', 'XXL'],
          colors: ['Schwarz'],
          badge: 'Bestseller',
          estimatedDeliveryTime: '7 bis 10 Werktage',
        },
        {
          id: 'crew-hoodie-flame',
          name: 'Crew Hoodie Flame',
          description: 'Schwerer Hoodie für Crew, Partner und Supporter mit orangem Rückenprint.',
          price: 59,
          sizes: ['M', 'L', 'XL', 'XXL'],
          colors: ['Schwarz', 'Anthrazit'],
          badge: 'Neu',
          estimatedDeliveryTime: '10 bis 14 Werktage',
        },
        {
          id: 'festival-cap-steel',
          name: 'Festival Cap Steel',
          description: 'Bestickte Cap für sonnige Festivaltage und den Look zwischen Werkstatt und Infield.',
          price: 24,
          colors: ['Schwarz', 'Dark Sand'],
          badge: 'Limited',
          estimatedDeliveryTime: '7 bis 10 Werktage',
        },
      ],
    },
    gallery: {
      eyebrow: 'Galerie',
      title: 'Einblicke in Headbang Handwerk.',
      lead: 'Bilder aus Projekten, Veranstaltungen und Aktionen. Öffne einen Ordner und sieh dir die Aufnahmen in voller Größe an.',
      folders: [],
    },
    footer: {
      brandHeadline: 'Headbang Handwerk',
      brandHighlight: ' - wir bringen das Handwerk auf die Bühne.',
      description:
        'Handwerk. Laut. Sichtbar. Wir verbinden Handwerk und Metal, fördern Nachwuchs und machen unser Handwerk auf den großen Bühnen sichtbar.',
      copyrightName: 'Headbang Handwerk e.V.',
      socialLinks: [
        { platform: 'facebook', label: 'Facebook', href: '' },
        { platform: 'instagram', label: 'Instagram', href: 'https://www.instagram.com/headbang.handwerk/' },
        { platform: 'tiktok', label: 'TikTok', href: '' },
        { platform: 'youtube', label: 'YouTube', href: '' },
      ],
      informationHeading: 'Informationen',
      informationLinks: [
        { id: 'about', label: 'Über uns', href: '/ueber-uns' },
        { id: 'events', label: 'Veranstaltungen', href: '/veranstaltungen' },
        { id: 'membership', label: 'Mitglied werden', href: '/formular' },
        { id: 'partners', label: 'Partner', href: '/unsere-partner' },
      ],
      contactHeading: 'Kontakt',
      contactLinks: [{ id: 'contact', label: 'Kontaktseite', href: '/kontakt' }],
      contactEmail: '',
    },
  },
};